name: Clojure CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Clojure Yools
        uses: DeLaGuardo/setup-clojure@3.2
        with:
          cli: 1.10.3.822

      - name: Build Jar
        run: clojure -X:jar
      
      - name: Deploy Jar
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: clojure -X:deploy
        env:
          CLOJARS_USERNAME: fbeyer
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_DEPLOY_TOKEN }}
